# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1162, 821)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.readButton = QtWidgets.QPushButton(self.centralwidget)
        self.readButton.setGeometry(QtCore.QRect(40, 720, 93, 28))
        self.readButton.setObjectName("readButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(160, 720, 93, 28))
        self.closeButton.setObjectName("closeButton")
        self.pictureLabel = QtWidgets.QLabel(self.centralwidget)
        self.pictureLabel.setGeometry(QtCore.QRect(20, 30, 451, 411))
        self.pictureLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pictureLabel.setMouseTracking(False)
        self.pictureLabel.setStyleSheet("background-color: rgb(200, 194, 197);")
        self.pictureLabel.setText("")
        self.pictureLabel.setObjectName("pictureLabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(850, 570, 220, 55))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit1.setObjectName("lineEdit1")
        self.horizontalLayout_2.addWidget(self.lineEdit1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit2.setObjectName("lineEdit2")
        self.horizontalLayout.addWidget(self.lineEdit2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 460, 121, 19))
        self.checkBox.setObjectName("checkBox")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 460, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pictureLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.pictureLabel_2.setGeometry(QtCore.QRect(490, 30, 451, 411))
        self.pictureLabel_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pictureLabel_2.setMouseTracking(False)
        self.pictureLabel_2.setStyleSheet("background-color: rgb(200, 194, 197);")
        self.pictureLabel_2.setText("")
        self.pictureLabel_2.setObjectName("pictureLabel_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 720, 93, 28))
        self.pushButton.setObjectName("pushButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1162, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        mainWindow.setMenuBar(self.menuBar)
        self.action_open = QtWidgets.QAction(mainWindow)
        self.action_open.setObjectName("action_open")
        self.action_2 = QtWidgets.QAction(mainWindow)
        self.action_2.setObjectName("action_2")
        self.actionSobel = QtWidgets.QAction(mainWindow)
        self.actionSobel.setCheckable(True)
        self.actionSobel.setEnabled(True)
        self.actionSobel.setObjectName("actionSobel")
        self.action_about = QtWidgets.QAction(mainWindow)
        self.action_about.setCheckable(True)
        self.action_about.setObjectName("action_about")
        self.menu.addAction(self.action_open)
        self.menu_2.addAction(self.action_2)
        self.menu_4.addAction(self.actionSobel)
        self.menu_5.addAction(self.action_about)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())

        self.retranslateUi(mainWindow)
        self.closeButton.clicked.connect(mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "机器视觉软件"))
        self.readButton.setText(_translate("mainWindow", "读取图片"))
        self.closeButton.setText(_translate("mainWindow", "关闭"))
        self.label_2.setText(_translate("mainWindow", "参数1"))
        self.label.setText(_translate("mainWindow", "参数2"))
        self.checkBox.setText(_translate("mainWindow", "checkbox"))
        self.comboBox.setItemText(0, _translate("mainWindow", "bmp"))
        self.comboBox.setItemText(1, _translate("mainWindow", "jpg"))
        self.comboBox.setItemText(2, _translate("mainWindow", "png"))
        self.pushButton.setText(_translate("mainWindow", "多线程"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.menu.setTitle(_translate("mainWindow", "文件"))
        self.menu_2.setTitle(_translate("mainWindow", "编辑"))
        self.menu_3.setTitle(_translate("mainWindow", "平滑滤波"))
        self.menu_4.setTitle(_translate("mainWindow", "边缘检测"))
        self.menu_5.setTitle(_translate("mainWindow", "帮助"))
        self.action_open.setText(_translate("mainWindow", "打开"))
        self.action_2.setText(_translate("mainWindow", "复制"))
        self.actionSobel.setText(_translate("mainWindow", "Sobel边缘检测"))
        self.action_about.setText(_translate("mainWindow", "关于"))

